(() => {
  const footer = `<div class="hunthings-footer__columns"><section><h2>Explore</h2><a href="/explore/style/">Style</a><a href="/explore/beauty/">Beauty</a><a href="/explore/home/">Home</a><a href="/explore/lifestyle/">Lifestyle</a><a href="/explore/tech/">Tech</a><a href="/explore/health/">Health</a><a href="/explore/hobbies/">Hobbies</a><a href="/explore/aesthetics/">Aesthetics</a></section><section><h2>Tools</h2><a href="/tools/patient-manager/">Patient Manager</a><a href="/tools/life-planner/">Life Planner</a><a href="/tools/content-hub/">Content Hub</a></section><section><h2>Products</h2><a href="/products/bestsellers/">Bestsellers</a><a href="/products/new/">New</a><a href="/products/editors-pick/">Editor's Pick</a><a href="/products/trending/">Trending</a><a href="/products/essential/">Essential</a></section><section><h2>Site</h2><a href="/about/">About</a><a href="/contact/">Contact</a><a href="/search/">Search</a></section><section><h2>Legal</h2><a href="/privacy-policy/">Privacy Policy</a><a href="/terms-of-use/">Terms of Use</a><a href="/affiliate-disclosure/">Affiliate Disclosure</a></section></div><div class="hunthings-footer__signature"><img src="/assets/logo-completo.webp" alt="hunthings"><span>© 2025 Hunthings.Co. All rights reserved.</span></div>`;
  const isComingSoon = () => ['/explore/style/', '/explore/home/', '/explore/hobbies/', '/explore/health/'].includes(location.pathname);
  function setFooters() { document.querySelectorAll('footer').forEach((node) => { if (!node.dataset.hunthingsFooter) { node.dataset.hunthingsFooter = 'true'; node.innerHTML = footer; } }); }
  function updateCookieBanner() { document.querySelectorAll('span').forEach((span) => { if (/Usamos cookies|We use cookies/.test(span.textContent)) span.innerHTML = 'We use cookies to improve your experience and personalize content.<br>See our <a href="/privacy-policy/" style="color: white; text-decoration: underline;">Privacy Policy</a>.'; }); document.querySelectorAll('button').forEach((button) => { if (/^Aceitar$|^Accept$/.test(button.textContent.trim())) button.textContent = 'Accept'; }); }
  function removeSkincareFeature() { document.querySelectorAll('section').forEach((section) => { const content = section.textContent.replace(/\s+/g, ' ').trim(); if (content.includes('Hunthings Tools') && content.includes('Skincare Organizer') && content.length < 900) section.remove(); }); }
  function addComingSoon() { if (!isComingSoon() || document.querySelector('.hunthings-coming-soon')) return; const screen = document.querySelector('[data-screen-label]'); const footerNode = document.querySelector('footer'); if (!screen || !footerNode) return; [...screen.children].filter((el) => el.tagName === 'SECTION').forEach((el) => { el.hidden = true; }); footerNode.insertAdjacentHTML('beforebegin', `<main class="hunthings-coming-soon"><div class="hunthings-coming-soon__inner"><h1>Good things take a little longer.</h1><p>We're carefully putting this together. Every page on Hunthings is designed to be genuinely useful.</p><h3>Want to be the first to know when it's ready?</h3><form><input type="email" required placeholder="Email address" aria-label="Email address"><button type="submit">Notify me</button></form></div></main>`); }
  function enhanceBlogCarousels() { document.querySelectorAll('section').forEach((section) => { const track = section.querySelector('div[style*="overflow-x: auto"]'); if (!track || !/Get yours/.test(track.textContent) || section.classList.contains('hunthings-product-carousel')) return; section.classList.add('hunthings-product-carousel'); track.classList.add('hunthings-product-carousel__track'); track.insertAdjacentHTML('beforebegin', '<button class="hunthings-product-carousel__arrow hunthings-product-carousel__arrow--prev" aria-label="Previous products">‹</button>'); track.insertAdjacentHTML('afterend', '<button class="hunthings-product-carousel__arrow hunthings-product-carousel__arrow--next" aria-label="Next products">›</button>'); section.querySelector('.hunthings-product-carousel__arrow--prev').addEventListener('click', () => track.scrollBy({ left: -320, behavior: 'smooth' })); section.querySelector('.hunthings-product-carousel__arrow--next').addEventListener('click', () => track.scrollBy({ left: 320, behavior: 'smooth' })); }); }
  function updatePostCuration() { document.querySelectorAll('h2').forEach((heading) => { if (/Curadoria/.test(heading.textContent)) { heading.textContent = 'Get yours'; heading.style.fontSize = '45px'; heading.style.lineHeight = '1.06'; const copy = heading.parentElement && heading.parentElement.querySelector('p'); if (copy) { copy.textContent = 'Editor-tested products that could be arriving at your door soon.'; copy.style.fontFamily = "'Inter', sans-serif"; copy.style.fontSize = '17px'; copy.style.lineHeight = '1.55'; copy.style.maxWidth = '560px'; } } }); }
  function enhance() { setFooters(); updateCookieBanner(); removeSkincareFeature(); addComingSoon(); updatePostCuration(); enhanceBlogCarousels(); }
  const observer = new MutationObserver(() => enhance()); observer.observe(document.documentElement, { childList: true, subtree: true }); window.addEventListener('DOMContentLoaded', enhance); setTimeout(enhance, 150);
})();
